version: '3.1'

# Path: Coyn/docker-compose.yml

services:

  api:
    container_name: coyn_api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
        - "5225:80"
    depends_on:
      - db
    
      
  db:
    container_name: coyn_db
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: coyn
      MARIADB_PASSWORD: ZVzmWmtAJviC3G
      MARIADB_ROOT_PASSWORD: PGnMM7KFRykcjA
      MARIADB_DATABASE: coyn
    ports:
      - '3309:3306'

networks:
  coyn:
    driver: bridge